input_data_path: "data/heart_cleveland_upload.csv"
output_model_path: "models/CatBoostClassifier/model.pkl"
metric_path: "models/CatBoostClassifier/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 3
train_params:
  model_type: "CatBoostClassifier"
  depth: 4
  iterations: 70
  learning_rate: 0.03
feature_params:

  numerical_features:
    - "age"
    - "sex"
    - "cp"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
  target_col: "condition"

