input_data_path: "data/heart_cleveland_upload.csv"
output_model_path: "models/DecisionTreeClassifier/model.pkl"
metric_path: "models/DecisionTreeClassifier/metrics.json"
splitting_params:
  val_size: 0.3
  random_state: 4
train_params:
  model_type: "DecisionTreeClassifier"
  max_depth: 8
  random_state: 42

feature_params:

  numerical_features:
    - "age"
    - "sex"
    - "cp"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
  target_col: "condition"

