name: Code checks

on:
  push:
    branches: [homework1]
  pull_request:
    branches: [homework1]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8 train pipe
        run: flake8 ./ml_project/train_pipeline.py
      - name: Run flake8 classes
        run: flake8 ./ml_project/classes/*
      - name: Run flake8 cfg
        run: flake8 ./ml_project/enities/cfg.py

